### ISSUE TITLE
Static IP in /etc/hosts

### ISSUE THREAD

**Issue by aminvakil** [atorrescogollo/linux-ansible#3]
Some documentations suggest using static IP in `/etc/hosts` if you have an static IP like:
https://wiki.archlinux.org/index.php/Installation_guide#Network_configuration
> If the system has a permanent IP address, it should be used instead of 127.0.1.1. 

Some require your static IP to be in `/etc/hosts` like:
https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster#Add_an_.2Fetc.2Fhosts_entry_for_your_IP_address
> Note: This also means editing or rather removing the address 127.0.1.1 that might be present as default. 

This task removes that line from `/etc/hosts` if it's needed.
https://github.com/atorrescogollo/linux-ansible/blob/65b678419b103e66bc7a5705633fd6ce62ca7e75/tasks/setup_hostname.yml#L6-L19

**Comment by aminvakil** [comment]
I use `lineinfile` for this change in `/etc/hosts` like this:
https://github.com/aminvakil/ansible-role-os-initialize/blob/d50fa8f119321f6b53eac22b0cdffe78e99c15be/tasks/debian.yml#L34-L39

But if you feel it's unnecessary, feel free to close this issue ;-)

**Comment by atorrescogollo** [comment]
Good point!

This configuration is only for static IPs which is not automated yet. For DHCP, it does not make sense so I find it unnecessary. However, I'll take this issue into account when when static IP config is automated.

Thank for submitting this issue :)
